spring:
  application:
    name: ThreadPool
#  task:
#    execution:
#      pool:
#        core-size: 10
#        max-size: 20
#        queue-capacity: 100
#        keep-alive: 60s
#      thread-name-prefix: async-

